# Generated by Django 2.2.7 on 2019-12-13 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest_status', models.CharField(max_length=30)),
                ('latest_update', models.DateField()),
            ],
        ),
    ]
