# Generated by Django 2.2.7 on 2019-12-13 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo_module', '0002_auto_20191213_1117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='latest_power_state',
            new_name='latest_power_code',
        ),
    ]
