# Generated by Django 2.2.10 on 2020-02-23 09:00

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_module', '0005_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inbound_payload', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.AlterField(
            model_name='status',
            name='latest_power_code',
            field=models.CharField(choices=[('600', '600 Device on'), ('610', '610 Device in hibernation'), ('620', '620 Device off')], default='620', max_length=3),
        ),
        migrations.AlterField(
            model_name='status',
            name='latest_status_code',
            field=models.CharField(choices=[('200', '200 OK'), ('202', '202 Received and accepted'), ('400', '400 Bad request'), ('404', '404 Not found'), ('405', '405 Method not allowed'), ('500', '500 Internal error on device')], default='200', max_length=3),
        ),
    ]
