# Generated by Django 2.2.12 on 2020-04-18 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_module', '0007_auto_20200322_0755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nd_ts',
            name='StatusCode',
        ),
        migrations.AddField(
            model_name='nd_ts',
            name='Statusbool',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='status',
            name='latest_power_code',
            field=models.CharField(choices=[('600', '600 Device on'), ('610', '610 Device off')], default='620', max_length=3),
        ),
    ]
