# Generated by Django 2.2.12 on 2020-04-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_module', '0008_auto_20200418_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nd_ts',
            name='Statusbool',
            field=models.BooleanField(default=True),
        ),
    ]
