version: '3.7'

services:
  webinterface:
    build: ./webinterface
    restart: unless-stopped
    image: janusboandersen/auwebinterface2020:webinterface
    ports:
      - "8001:8001"
    volumes:
      - ./webinterface/:/usr/src/webinterface/
      - ./staticassets/:/var/www/static/
      - static_volume:/usr/src/webinterface/staticfiles/
    env_file:
      - ./.env.webinterface
    depends_on:
      - db
    command: >
      python manage.py runserver 0.0.0.0:8001

  db:
    image: postgres:12.0-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - data-volume:/var/lib/postgresql/data/
    env_file:
      - ./.env.db


  mqtt:
    image: eclipse-mosquitto:1.6
    hostname: mosquitto
    ports:
      - "8000:8000"
      - "8883:8883"
      - "8081:8081"
    volumes:
      - ./mosquitto/config/:/mosquitto/config/
      - mqtt-volume:/mosquitto/data
      - mqtt-volume:/mosquitto/log

  nginx:
    image: nginx:mainline-alpine
    depends_on:
      - webinterface
    restart: unless-stopped
    volumes:
      - web-root:/var/www/html
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/usr/src/webinterface/staticfiles/
    ports:
      - "81:80"
      - "444:443"

#  certbot:
#    image: certbot/certbot
#    volumes:
#      # This will mount the relevant Let’s Encrypt certificates,
#      # and keys for our domain to the appropriate directory on the container.
#      - certbot-etc:/etc/letsencrypt
#      - certbot-var:/var/lib/letsencrypt
#      - web-root:/var/www/html
#    depends_on:
#      - nginx
#    command: certonly --webroot --webroot-path=/var/www/html --email team2@team2.not-a-real-e-mail.au --agree-tos --staging -d auteam2.mooo.com:81  -d www.auteam2.mooo.com:81

  videostream:
    build:
      context: ./videostream/image
    image: janusboandersen/auwebinterface2020:videostream
    restart: always
    env_file:
      - ./videostream/instance/vstream.env
    volumes:
      - ./videostream/:/usr/src/videostream/
      - ./webinterface/:/usr/src/webinterface/
    ports:
      - "5555:5555"

volumes:
  web-root:
  certbot-etc:
  certbot-var:
  static_volume:
  data-volume:
    external: true
  mqtt-volume:
    external: true
