version: '3.7'

services:
  webinterface:
    build: ./webinterface
    ports:
      - "8000:8000"
    volumes:
      - ./webinterface/:/usr/src/webinterface/
    env_file:
      - ./.env.webinterface
    depends_on:
      - db
    command: >
      python manage.py runserver 0.0.0.0:8000

  db:
    image: postgres:12.0-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - data-volume:/var/lib/postgresql/data/
    env_file:
      - ./.env.db

  mqtt:
    image: eclipse-mosquitto:1.6
    hostname: mosquitto
    ports:
      - "1883:1883"
      - "8883:8883"
      - "8081:8081"
    volumes:
      - ./mosquitto/config/:/mosquitto/config/
      - mqtt-volume:/mosquitto/data
      - mqtt-volume:/mosquitto/log

#Webserver docker
  nginx:
    image: nginx
    depends_on:
      - db
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "81:80"
      - "444:443"

volumes:
  data-volume:
    external: true
  mqtt-volume:
    external: true
