version: '3.7'

services:

  webinterface:
    build: ./webinterface
    ports:
      - "8001:8001"
    volumes:
      - //c/docker/webinterface/:/usr/src/webinterface/
      - //c/docker/staticassets/:/var/www/static/
      - static_volume:/usr/src/webinterface/staticfiles/
    env_file:
      - ./.env.webinterface
    depends_on:
      - db
    command: python manage.py runserver 0.0.0.0:8001


  db:
    image: postgres:12.0-alpine
    restart: always
    volumes:
      - data-volume:/var/lib/postgresql/data/
    env_file:
      - ./.env.db


  mqtt:
    image: eclipse-mosquitto:1.6
    hostname: mosquitto
    ports:
      - "8000:8000"
      - "8883:8883"
      - "8081:8081"
    volumes:
      - //c/docker/mosquitto/config/:/mosquitto/config/
      - mqtt-volume:/mosquitto/data
      - mqtt-volume:/mosquitto/log

  nginx:
    image: nginx
    depends_on:
      - webinterface
    restart: always
    volumes:
      - //c/docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/usr/src/webinterface/staticfiles/
    ports:
      - "81:80"
      - "444:443"

volumes:
  static_volume:
  data-volume:
    external: true
  mqtt-volume:
    external: true
