version: '3.7'

services:

  webinterface:
    build: ./webinterface
    ports:
      - "8000:8000"
    volumes:
      - //c/docker/webinterface/:/usr/src/webinterface/
    depends_on:
      - db
    command: python manage.py runserver 0.0.0.0:8000


  db: 
    image: postgres:12.0-alpine
    restart: always
    volumes: 
      - data-volume:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=team2
      - POSTGRES_PASSWORD=team2
        POSTGRES_DB=webinterface_dev


  mqtt:
    image: eclipse-mosquitto
    hostname: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - //c/docker/mosquitto/config/:/mosquitto/config/
      - mqtt-volume:/mosquitto/data
      - mqtt-volume:/mosquitto/log


  nginx:
    image: nginx
    depends_on:
      - db
    restart: always
    ports:
      - "81:80"
      - "444:443"

volumes:
  data-volume:
    external: true
  mqtt-volume:
    external: true
