# Generated by Django 2.2.7 on 2019-11-28 14:31


from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='testdatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data', models.CharField(max_length=100)),
                ('Timestamp', models.DateTimeField(auto_now=True)),
                ('NODELETE', models.BooleanField(default=False)),
            ],
        ),
    ]
